setwd("/Users/mac/Documents/coursera/ExData_Plotting1/")
data <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE, skip = 66636, nrows = 2880)
columnNames <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE, nrows = 1)
names(data) <- names(columnNames)
data$DateTime <- strptime(paste(data$Date, data$Time) , format = "%d/%m/%Y %H:%M:%S")
png(filename = "./plot3.png")
plot(data$DateTime, data$Sub_metering_1, type = "l", col = "black",ylab = "Energy sub metering", xlab = "", main = "")
lines(data$DateTime, data$Sub_metering_2, col = "red")
lines(data$DateTime, data$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_meeting_1", "Sub_meeting_2", "Sub_meeting_3"))
dev.off()