setwd("/Users/mac/Documents/coursera/ExData_Plotting1/")
data <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE, skip = 66636, nrows = 2880)
columnNames <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE, nrows = 1)
names(data) <- names(columnNames)
data$datetime <- strptime(paste(data$Date, data$Time) , format = "%d/%m/%Y %H:%M:%S")
png(filename = "./plot4.png")
par(mfrow = c(2,2))
plot(data$datetime, data$Global_active_power, type = "l", ylab = "Global Active Power", xlab = "", main = "")
plot(data$datetime, data$Voltage, type = "l", ylab = "Voltage", xlab = "datetime", main = "")
plot(data$datetime, data$Sub_metering_1, type = "l", col = "black",ylab = "Energy sub metering", xlab = "", main = "")
lines(data$datetime, data$Sub_metering_2, col = "red")
lines(data$datetime, data$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_meeting_1", "Sub_meeting_2", "Sub_meeting_3"))
plot(data$datetime, data$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime", main = "")
dev.off()